sunpy/sunraster

- irispy/tests/test_iris_tools.py
- irispy/tests/test_sji.py
- irispy/tests/test_spectrograph.py
This PR adds files to be using for writing tests for iris_tools.py, sji.py and spectrograph.py.
> Added testing directory

- irispy/spectrograph.py
Added empty __init__.py file so modules within irispy can be import into others within irispy.
> Added __init__.py

- irispy/mapcubed.py
Copied mapcubed module from ehsteve's sunpy PR so we can start work with it while the PR is being finished and merged into sunpy.
> Copied mapcubed module from ehsteve's sunpy PR

- irispy_requirements.md
Altered indentation of subnested bullets to try to ensure they are correctly rendered.
> Altered indentation of subnested bullets

- irispy/sji.py
- irispy/sji_test.py
new sji movie tools ready for review
> sji movie tools

- ah_bootstrap.py
Upadated.
@DanRyanIrish 
try to install it now :)
> Updated astropy-helpers to v2.0.0

- irispy/spectrograph.py
> adding the NDCube

- .rtd-environment.yml
- .travis.yml
- docs/conf.py
- docs/index.rst
- docs/irispy.rst
- docs/mapcubed.rst
- docs/sji.rst
- docs/spectrograph.rst
- irispy/mapcubed.py
- irispy/sji.py
- irispy/spectrograph.py
- irispy/tests/test_sji.py
- setup.cfg
> docs build branch

- irispy/spectrograph.py
- irispy/tests/test_SpectrogramSequence.py
initial commit now working :)
@DanRyanIrish
> adding the new SpectrogramSequence

- irispy/spectrogram.py
- irispy/spectrograph.py
Change IRISSpectrograph's data storage object from NDCubeSequence to SpectrogramSequence.
Also added a repr string to SpectrogramSequence.
> Make IRISSpectrograph Use SepectrogramSequence for Data

- irispy/spectrogram.py
- irispy/spectrograph.py
This PR makes some minor updates to accommodate ndcube's change of NDCube._extra_coords and NDC…ubeSequence._common_axis_extra_coords change to public attributes.
> Update for ndcube attribute name changes.

- irispy/iris_tools.py
- irispy/new_sji.py
- irispy/sji.py
The first version of the new SJICube class using NDCube. Most of this class comes from the old SJICube class.
> Adding SJICube class using NDCube

- irispy/new_sji.py
- irispy/tests/test_new_sji.py
Here the first version of the time correction function for SJICube.
> Adding a time correction function to SJICube

- docs/api.rst
- docs/contributing.rst
- docs/getting_help.rst
- docs/index.rst
- docs/installation.rst
- docs/introduction.rst
This PR adds a set of installation instructions and a guide on how to contribute to IRISpy to the docs.
> Add Installation and Contributing Guide to Docs

- irispy/new_sji.py
- irispy/spectrograph.py
- irispy/tests/test_new_sji.py
- irispy/tests/test_spectrograph.py
Here the PR about the #73 discussion.
> New naming convention from SJICube and IRISSpectrogram

- irispy/spectrograph.py
This is an attempt to fix some of the problems in #79.
> Getting a better __repr__ for IRISSpectrograph

- irispy/new_sji.py
- irispy/tests/test_new_sji.py
Here some tests for IRISMapCubeSequence.
> Add tests for IRISMapCubeSequence

- irispy/iris_tools.py
- irispy/new_sji.py
- irispy/tests/test_iris_tools.py
- irispy/tests/test_new_sji.py
Hi @DanRyanIrish , some lines to begin to speak about the dust mask function. For now, I set `NaN` to values under 0.5 that is match with dust particles position. This will be modified, that was just to check some code lines.
What kind of dust mask do you want ? A mask ? `NaN` data ? A file ?
> Creation of dust mask function

- irispy/spectrograph.py
This PR reduces the RAM needed during reading spectrograph files without changing the final output, except that masked values remain -200 rather than replaced with NaNs.  This operation was highlighted as a significant RAM drain in issue #82.
> Remove conversion of -200 to NaN in read_iris_spectrograph_level2_fits.

- irispy/iris_tools.py
- irispy/tests/test_iris_tools.py
Aim 
===
To complete the basic tests for IRISpy to run smoothly.
> Complete basic testing for IRISpy

- README.md
- contributing.md
- docs/contributing.rst
- docs/getting_help.rst
- docs/index.rst
- docs/installation.rst
- docs/introduction.rst
- docs/sunraster.rst
- setup.cfg
- setup.py
- sunraster/data/setup_package.py
- sunraster/raster.py
This PR continues the transition of IRISpy to sunraseter.  It updates the package name in a number of locations and improves the aesthetic output of some properties of the Raster classes.
> Rasterpy to sunraster

- sunraster/__init__.py
The PR continues the transition from IRISpy to sunraster.
> Transition to sunraster

- irispy/sji.py
Fixes #92 
I have removed mentioned classes from `irispy/sji.py`
> removed old SJI classes

- README.md
Update the `README.md` doc to reflect change in package name, and also update copyright symbol in doc.
> Update name and copyright symbol in README

- sunraster/spectrogram_sequence.py
Previously this raised a NotImplementedError to encourage users to use
the slice_as_raster property. But the regular API is needed so it plays
nicely within the ndcube ecosystem, e.g. so NDCollection can slice
RasterSequences.
Addresses Issue #149
> Reimplement basic RasterSequence slicing API

- .circleci/config.yml
- .codecov.yaml
- azure-pipelines.yml
- docs/api.rst
- docs/conf.py
- docs/contributing.rst
- docs/data_classes.rst
- sunraster/__init__.py
- sunraster/io/iris.py
- sunraster/spectrogram.py
- sunraster/spectrogram_sequence.py
- sunraster/tests/test_spectrogram.py
- sunraster/tests/test_spectrogramsequence.py
- tox.ini
Fixes #151
I don't think this is worth merging in.
> CI build for ndcube 1.3 branch

- README.rst
- docs/contributing.rst
- docs/data_classes.rst
- docs/index.rst
- docs/installation.rst
- docs/introduction.rst
Addresses #143, potentially fixing the issue. 
1. Have proofread the docs. 
2. Have studied the docs and concluded that the length of content is just right for the intended scope.
> Proofreading of sunraster docs

- sunraster/instr/spice.py
- sunraster/tests/test_spice.py
> Fix SPICE reader calculation of aligned axes.

- setup.cfg
- sunraster/instr/iris.py
- sunraster/tests/test_spectrogram.py
Need to wait for a the bugfix release of ndcube.
> unskip test and prepare for ndcube 2.0.1

- .github/workflows/ci.yml
- CHANGELOG.rst
- setup.cfg
- tox.ini
Going to tag a RC for 0.5.0 so I can use it downstream.
> Update for sunpy 5.0 and ndcube 2.1.2

- pyproject.toml
- sunraster/spectrogram.py
- tox.ini
> Remove unneeded parts of tox.ini

- .cruft.json
- .github/workflows/ci.yml
- tox.ini
This PR has been generated by a script, it should update the repo with the latest changes from the package template.
> Updates from package template
